// automatically generated by the FlatBuffers compiler, do not modify

import { AbsOptions } from "@/utils/tflite/tflite/abs-options";
import { AddNOptions } from "@/utils/tflite/tflite/add-noptions";
import { AddOptions } from "@/utils/tflite/tflite/add-options";
import { ArgMaxOptions } from "@/utils/tflite/tflite/arg-max-options";
import { ArgMinOptions } from "@/utils/tflite/tflite/arg-min-options";
import { AssignVariableOptions } from "@/utils/tflite/tflite/assign-variable-options";
import { ATan2Options } from "@/utils/tflite/tflite/atan2-options";
import { BatchMatMulOptions } from "@/utils/tflite/tflite/batch-mat-mul-options";
import { BatchToSpaceNDOptions } from "@/utils/tflite/tflite/batch-to-space-ndoptions";
import { BidirectionalSequenceLSTMOptions } from "@/utils/tflite/tflite/bidirectional-sequence-lstmoptions";
import { BidirectionalSequenceRNNOptions } from "@/utils/tflite/tflite/bidirectional-sequence-rnnoptions";
import { BitcastOptions } from "@/utils/tflite/tflite/bitcast-options";
import { BitwiseXorOptions } from "@/utils/tflite/tflite/bitwise-xor-options";
import { BroadcastToOptions } from "@/utils/tflite/tflite/broadcast-to-options";
import { BucketizeOptions } from "@/utils/tflite/tflite/bucketize-options";
import { CallOnceOptions } from "@/utils/tflite/tflite/call-once-options";
import { CallOptions } from "@/utils/tflite/tflite/call-options";
import { CastOptions } from "@/utils/tflite/tflite/cast-options";
import { ConcatEmbeddingsOptions } from "@/utils/tflite/tflite/concat-embeddings-options";
import { ConcatenationOptions } from "@/utils/tflite/tflite/concatenation-options";
import { Conv2DOptions } from "@/utils/tflite/tflite/conv2-doptions";
import { Conv3DOptions } from "@/utils/tflite/tflite/conv3-doptions";
import { CosOptions } from "@/utils/tflite/tflite/cos-options";
import { CumsumOptions } from "@/utils/tflite/tflite/cumsum-options";
import { DensifyOptions } from "@/utils/tflite/tflite/densify-options";
import { DepthToSpaceOptions } from "@/utils/tflite/tflite/depth-to-space-options";
import { DepthwiseConv2DOptions } from "@/utils/tflite/tflite/depthwise-conv2-doptions";
import { DequantizeOptions } from "@/utils/tflite/tflite/dequantize-options";
import { DivOptions } from "@/utils/tflite/tflite/div-options";
import { DynamicUpdateSliceOptions } from "@/utils/tflite/tflite/dynamic-update-slice-options";
import { EmbeddingLookupSparseOptions } from "@/utils/tflite/tflite/embedding-lookup-sparse-options";
import { EqualOptions } from "@/utils/tflite/tflite/equal-options";
import { ExpOptions } from "@/utils/tflite/tflite/exp-options";
import { ExpandDimsOptions } from "@/utils/tflite/tflite/expand-dims-options";
import { FakeQuantOptions } from "@/utils/tflite/tflite/fake-quant-options";
import { FillOptions } from "@/utils/tflite/tflite/fill-options";
import { FloorDivOptions } from "@/utils/tflite/tflite/floor-div-options";
import { FloorModOptions } from "@/utils/tflite/tflite/floor-mod-options";
import { FullyConnectedOptions } from "@/utils/tflite/tflite/fully-connected-options";
import { GatherNdOptions } from "@/utils/tflite/tflite/gather-nd-options";
import { GatherOptions } from "@/utils/tflite/tflite/gather-options";
import { GeluOptions } from "@/utils/tflite/tflite/gelu-options";
import { GreaterEqualOptions } from "@/utils/tflite/tflite/greater-equal-options";
import { GreaterOptions } from "@/utils/tflite/tflite/greater-options";
import { HardSwishOptions } from "@/utils/tflite/tflite/hard-swish-options";
import { HashtableFindOptions } from "@/utils/tflite/tflite/hashtable-find-options";
import { HashtableImportOptions } from "@/utils/tflite/tflite/hashtable-import-options";
import { HashtableOptions } from "@/utils/tflite/tflite/hashtable-options";
import { HashtableSizeOptions } from "@/utils/tflite/tflite/hashtable-size-options";
import { IfOptions } from "@/utils/tflite/tflite/if-options";
import { L2NormOptions } from "@/utils/tflite/tflite/l2-norm-options";
import { LeakyReluOptions } from "@/utils/tflite/tflite/leaky-relu-options";
import { LessEqualOptions } from "@/utils/tflite/tflite/less-equal-options";
import { LessOptions } from "@/utils/tflite/tflite/less-options";
import { LocalResponseNormalizationOptions } from "@/utils/tflite/tflite/local-response-normalization-options";
import { LogSoftmaxOptions } from "@/utils/tflite/tflite/log-softmax-options";
import { LogicalAndOptions } from "@/utils/tflite/tflite/logical-and-options";
import { LogicalNotOptions } from "@/utils/tflite/tflite/logical-not-options";
import { LogicalOrOptions } from "@/utils/tflite/tflite/logical-or-options";
import { LSHProjectionOptions } from "@/utils/tflite/tflite/lshprojection-options";
import { LSTMOptions } from "@/utils/tflite/tflite/lstmoptions";
import { MatrixDiagOptions } from "@/utils/tflite/tflite/matrix-diag-options";
import { MatrixSetDiagOptions } from "@/utils/tflite/tflite/matrix-set-diag-options";
import { MaximumMinimumOptions } from "@/utils/tflite/tflite/maximum-minimum-options";
import { MirrorPadOptions } from "@/utils/tflite/tflite/mirror-pad-options";
import { MulOptions } from "@/utils/tflite/tflite/mul-options";
import { NegOptions } from "@/utils/tflite/tflite/neg-options";
import { NonMaxSuppressionV4Options } from "@/utils/tflite/tflite/non-max-suppression-v4-options";
import { NonMaxSuppressionV5Options } from "@/utils/tflite/tflite/non-max-suppression-v5-options";
import { NotEqualOptions } from "@/utils/tflite/tflite/not-equal-options";
import { OneHotOptions } from "@/utils/tflite/tflite/one-hot-options";
import { PackOptions } from "@/utils/tflite/tflite/pack-options";
import { PadOptions } from "@/utils/tflite/tflite/pad-options";
import { PadV2Options } from "@/utils/tflite/tflite/pad-v2-options";
import { Pool2DOptions } from "@/utils/tflite/tflite/pool2-doptions";
import { PowOptions } from "@/utils/tflite/tflite/pow-options";
import { QuantizeOptions } from "@/utils/tflite/tflite/quantize-options";
import { RandomOptions } from "@/utils/tflite/tflite/random-options";
import { RangeOptions } from "@/utils/tflite/tflite/range-options";
import { RankOptions } from "@/utils/tflite/tflite/rank-options";
import { ReadVariableOptions } from "@/utils/tflite/tflite/read-variable-options";
import { ReducerOptions } from "@/utils/tflite/tflite/reducer-options";
import { ReshapeOptions } from "@/utils/tflite/tflite/reshape-options";
import { ResizeBilinearOptions } from "@/utils/tflite/tflite/resize-bilinear-options";
import { ResizeNearestNeighborOptions } from "@/utils/tflite/tflite/resize-nearest-neighbor-options";
import { ReverseSequenceOptions } from "@/utils/tflite/tflite/reverse-sequence-options";
import { ReverseV2Options } from "@/utils/tflite/tflite/reverse-v2-options";
import { Rfft2dOptions } from "@/utils/tflite/tflite/rfft2d-options";
import { RightShiftOptions } from "@/utils/tflite/tflite/right-shift-options";
import { RNNOptions } from "@/utils/tflite/tflite/rnnoptions";
import { ScatterNdOptions } from "@/utils/tflite/tflite/scatter-nd-options";
import { SegmentSumOptions } from "@/utils/tflite/tflite/segment-sum-options";
import { SelectOptions } from "@/utils/tflite/tflite/select-options";
import { SelectV2Options } from "@/utils/tflite/tflite/select-v2-options";
import { SequenceRNNOptions } from "@/utils/tflite/tflite/sequence-rnnoptions";
import { ShapeOptions } from "@/utils/tflite/tflite/shape-options";
import { SignOptions } from "@/utils/tflite/tflite/sign-options";
import { SkipGramOptions } from "@/utils/tflite/tflite/skip-gram-options";
import { SliceOptions } from "@/utils/tflite/tflite/slice-options";
import { SoftmaxOptions } from "@/utils/tflite/tflite/softmax-options";
import { SpaceToBatchNDOptions } from "@/utils/tflite/tflite/space-to-batch-ndoptions";
import { SpaceToDepthOptions } from "@/utils/tflite/tflite/space-to-depth-options";
import { SparseToDenseOptions } from "@/utils/tflite/tflite/sparse-to-dense-options";
import { SplitOptions } from "@/utils/tflite/tflite/split-options";
import { SplitVOptions } from "@/utils/tflite/tflite/split-voptions";
import { SquareOptions } from "@/utils/tflite/tflite/square-options";
import { SquaredDifferenceOptions } from "@/utils/tflite/tflite/squared-difference-options";
import { SqueezeOptions } from "@/utils/tflite/tflite/squeeze-options";
import { StridedSliceOptions } from "@/utils/tflite/tflite/strided-slice-options";
import { SubOptions } from "@/utils/tflite/tflite/sub-options";
import { SVDFOptions } from "@/utils/tflite/tflite/svdfoptions";
import { TileOptions } from "@/utils/tflite/tflite/tile-options";
import { TopKV2Options } from "@/utils/tflite/tflite/top-kv2-options";
import { TransposeConvOptions } from "@/utils/tflite/tflite/transpose-conv-options";
import { TransposeOptions } from "@/utils/tflite/tflite/transpose-options";
import { UnidirectionalSequenceLSTMOptions } from "@/utils/tflite/tflite/unidirectional-sequence-lstmoptions";
import { UniqueOptions } from "@/utils/tflite/tflite/unique-options";
import { UnpackOptions } from "@/utils/tflite/tflite/unpack-options";
import { UnsortedSegmentMaxOptions } from "@/utils/tflite/tflite/unsorted-segment-max-options";
import { UnsortedSegmentMinOptions } from "@/utils/tflite/tflite/unsorted-segment-min-options";
import { UnsortedSegmentProdOptions } from "@/utils/tflite/tflite/unsorted-segment-prod-options";
import { UnsortedSegmentSumOptions } from "@/utils/tflite/tflite/unsorted-segment-sum-options";
import { VarHandleOptions } from "@/utils/tflite/tflite/var-handle-options";
import { WhereOptions } from "@/utils/tflite/tflite/where-options";
import { WhileOptions } from "@/utils/tflite/tflite/while-options";
import { ZerosLikeOptions } from "@/utils/tflite/tflite/zeros-like-options";

export enum BuiltinOptions {
  NONE = 0,
  Conv2DOptions = 1,
  DepthwiseConv2DOptions = 2,
  ConcatEmbeddingsOptions = 3,
  LSHProjectionOptions = 4,
  Pool2DOptions = 5,
  SVDFOptions = 6,
  RNNOptions = 7,
  FullyConnectedOptions = 8,
  SoftmaxOptions = 9,
  ConcatenationOptions = 10,
  AddOptions = 11,
  L2NormOptions = 12,
  LocalResponseNormalizationOptions = 13,
  LSTMOptions = 14,
  ResizeBilinearOptions = 15,
  CallOptions = 16,
  ReshapeOptions = 17,
  SkipGramOptions = 18,
  SpaceToDepthOptions = 19,
  EmbeddingLookupSparseOptions = 20,
  MulOptions = 21,
  PadOptions = 22,
  GatherOptions = 23,
  BatchToSpaceNDOptions = 24,
  SpaceToBatchNDOptions = 25,
  TransposeOptions = 26,
  ReducerOptions = 27,
  SubOptions = 28,
  DivOptions = 29,
  SqueezeOptions = 30,
  SequenceRNNOptions = 31,
  StridedSliceOptions = 32,
  ExpOptions = 33,
  TopKV2Options = 34,
  SplitOptions = 35,
  LogSoftmaxOptions = 36,
  CastOptions = 37,
  DequantizeOptions = 38,
  MaximumMinimumOptions = 39,
  ArgMaxOptions = 40,
  LessOptions = 41,
  NegOptions = 42,
  PadV2Options = 43,
  GreaterOptions = 44,
  GreaterEqualOptions = 45,
  LessEqualOptions = 46,
  SelectOptions = 47,
  SliceOptions = 48,
  TransposeConvOptions = 49,
  SparseToDenseOptions = 50,
  TileOptions = 51,
  ExpandDimsOptions = 52,
  EqualOptions = 53,
  NotEqualOptions = 54,
  ShapeOptions = 55,
  PowOptions = 56,
  ArgMinOptions = 57,
  FakeQuantOptions = 58,
  PackOptions = 59,
  LogicalOrOptions = 60,
  OneHotOptions = 61,
  LogicalAndOptions = 62,
  LogicalNotOptions = 63,
  UnpackOptions = 64,
  FloorDivOptions = 65,
  SquareOptions = 66,
  ZerosLikeOptions = 67,
  FillOptions = 68,
  BidirectionalSequenceLSTMOptions = 69,
  BidirectionalSequenceRNNOptions = 70,
  UnidirectionalSequenceLSTMOptions = 71,
  FloorModOptions = 72,
  RangeOptions = 73,
  ResizeNearestNeighborOptions = 74,
  LeakyReluOptions = 75,
  SquaredDifferenceOptions = 76,
  MirrorPadOptions = 77,
  AbsOptions = 78,
  SplitVOptions = 79,
  UniqueOptions = 80,
  ReverseV2Options = 81,
  AddNOptions = 82,
  GatherNdOptions = 83,
  CosOptions = 84,
  WhereOptions = 85,
  RankOptions = 86,
  ReverseSequenceOptions = 87,
  MatrixDiagOptions = 88,
  QuantizeOptions = 89,
  MatrixSetDiagOptions = 90,
  HardSwishOptions = 91,
  IfOptions = 92,
  WhileOptions = 93,
  DepthToSpaceOptions = 94,
  NonMaxSuppressionV4Options = 95,
  NonMaxSuppressionV5Options = 96,
  ScatterNdOptions = 97,
  SelectV2Options = 98,
  DensifyOptions = 99,
  SegmentSumOptions = 100,
  BatchMatMulOptions = 101,
  CumsumOptions = 102,
  CallOnceOptions = 103,
  BroadcastToOptions = 104,
  Rfft2dOptions = 105,
  Conv3DOptions = 106,
  HashtableOptions = 107,
  HashtableFindOptions = 108,
  HashtableImportOptions = 109,
  HashtableSizeOptions = 110,
  VarHandleOptions = 111,
  ReadVariableOptions = 112,
  AssignVariableOptions = 113,
  RandomOptions = 114,
  BucketizeOptions = 115,
  GeluOptions = 116,
  DynamicUpdateSliceOptions = 117,
  UnsortedSegmentProdOptions = 118,
  UnsortedSegmentMaxOptions = 119,
  UnsortedSegmentMinOptions = 120,
  UnsortedSegmentSumOptions = 121,
  ATan2Options = 122,
  SignOptions = 123,
  BitcastOptions = 124,
  BitwiseXorOptions = 125,
  RightShiftOptions = 126,
}

export function unionToBuiltinOptions(
  type: BuiltinOptions,
  accessor: (
    obj:
      | ATan2Options
      | AbsOptions
      | AddNOptions
      | AddOptions
      | ArgMaxOptions
      | ArgMinOptions
      | AssignVariableOptions
      | BatchMatMulOptions
      | BatchToSpaceNDOptions
      | BidirectionalSequenceLSTMOptions
      | BidirectionalSequenceRNNOptions
      | BitcastOptions
      | BitwiseXorOptions
      | BroadcastToOptions
      | BucketizeOptions
      | CallOnceOptions
      | CallOptions
      | CastOptions
      | ConcatEmbeddingsOptions
      | ConcatenationOptions
      | Conv2DOptions
      | Conv3DOptions
      | CosOptions
      | CumsumOptions
      | DensifyOptions
      | DepthToSpaceOptions
      | DepthwiseConv2DOptions
      | DequantizeOptions
      | DivOptions
      | DynamicUpdateSliceOptions
      | EmbeddingLookupSparseOptions
      | EqualOptions
      | ExpOptions
      | ExpandDimsOptions
      | FakeQuantOptions
      | FillOptions
      | FloorDivOptions
      | FloorModOptions
      | FullyConnectedOptions
      | GatherNdOptions
      | GatherOptions
      | GeluOptions
      | GreaterEqualOptions
      | GreaterOptions
      | HardSwishOptions
      | HashtableFindOptions
      | HashtableImportOptions
      | HashtableOptions
      | HashtableSizeOptions
      | IfOptions
      | L2NormOptions
      | LSHProjectionOptions
      | LSTMOptions
      | LeakyReluOptions
      | LessEqualOptions
      | LessOptions
      | LocalResponseNormalizationOptions
      | LogSoftmaxOptions
      | LogicalAndOptions
      | LogicalNotOptions
      | LogicalOrOptions
      | MatrixDiagOptions
      | MatrixSetDiagOptions
      | MaximumMinimumOptions
      | MirrorPadOptions
      | MulOptions
      | NegOptions
      | NonMaxSuppressionV4Options
      | NonMaxSuppressionV5Options
      | NotEqualOptions
      | OneHotOptions
      | PackOptions
      | PadOptions
      | PadV2Options
      | Pool2DOptions
      | PowOptions
      | QuantizeOptions
      | RNNOptions
      | RandomOptions
      | RangeOptions
      | RankOptions
      | ReadVariableOptions
      | ReducerOptions
      | ReshapeOptions
      | ResizeBilinearOptions
      | ResizeNearestNeighborOptions
      | ReverseSequenceOptions
      | ReverseV2Options
      | Rfft2dOptions
      | RightShiftOptions
      | SVDFOptions
      | ScatterNdOptions
      | SegmentSumOptions
      | SelectOptions
      | SelectV2Options
      | SequenceRNNOptions
      | ShapeOptions
      | SignOptions
      | SkipGramOptions
      | SliceOptions
      | SoftmaxOptions
      | SpaceToBatchNDOptions
      | SpaceToDepthOptions
      | SparseToDenseOptions
      | SplitOptions
      | SplitVOptions
      | SquareOptions
      | SquaredDifferenceOptions
      | SqueezeOptions
      | StridedSliceOptions
      | SubOptions
      | TileOptions
      | TopKV2Options
      | TransposeConvOptions
      | TransposeOptions
      | UnidirectionalSequenceLSTMOptions
      | UniqueOptions
      | UnpackOptions
      | UnsortedSegmentMaxOptions
      | UnsortedSegmentMinOptions
      | UnsortedSegmentProdOptions
      | UnsortedSegmentSumOptions
      | VarHandleOptions
      | WhereOptions
      | WhileOptions
      | ZerosLikeOptions,
  ) =>
    | ATan2Options
    | AbsOptions
    | AddNOptions
    | AddOptions
    | ArgMaxOptions
    | ArgMinOptions
    | AssignVariableOptions
    | BatchMatMulOptions
    | BatchToSpaceNDOptions
    | BidirectionalSequenceLSTMOptions
    | BidirectionalSequenceRNNOptions
    | BitcastOptions
    | BitwiseXorOptions
    | BroadcastToOptions
    | BucketizeOptions
    | CallOnceOptions
    | CallOptions
    | CastOptions
    | ConcatEmbeddingsOptions
    | ConcatenationOptions
    | Conv2DOptions
    | Conv3DOptions
    | CosOptions
    | CumsumOptions
    | DensifyOptions
    | DepthToSpaceOptions
    | DepthwiseConv2DOptions
    | DequantizeOptions
    | DivOptions
    | DynamicUpdateSliceOptions
    | EmbeddingLookupSparseOptions
    | EqualOptions
    | ExpOptions
    | ExpandDimsOptions
    | FakeQuantOptions
    | FillOptions
    | FloorDivOptions
    | FloorModOptions
    | FullyConnectedOptions
    | GatherNdOptions
    | GatherOptions
    | GeluOptions
    | GreaterEqualOptions
    | GreaterOptions
    | HardSwishOptions
    | HashtableFindOptions
    | HashtableImportOptions
    | HashtableOptions
    | HashtableSizeOptions
    | IfOptions
    | L2NormOptions
    | LSHProjectionOptions
    | LSTMOptions
    | LeakyReluOptions
    | LessEqualOptions
    | LessOptions
    | LocalResponseNormalizationOptions
    | LogSoftmaxOptions
    | LogicalAndOptions
    | LogicalNotOptions
    | LogicalOrOptions
    | MatrixDiagOptions
    | MatrixSetDiagOptions
    | MaximumMinimumOptions
    | MirrorPadOptions
    | MulOptions
    | NegOptions
    | NonMaxSuppressionV4Options
    | NonMaxSuppressionV5Options
    | NotEqualOptions
    | OneHotOptions
    | PackOptions
    | PadOptions
    | PadV2Options
    | Pool2DOptions
    | PowOptions
    | QuantizeOptions
    | RNNOptions
    | RandomOptions
    | RangeOptions
    | RankOptions
    | ReadVariableOptions
    | ReducerOptions
    | ReshapeOptions
    | ResizeBilinearOptions
    | ResizeNearestNeighborOptions
    | ReverseSequenceOptions
    | ReverseV2Options
    | Rfft2dOptions
    | RightShiftOptions
    | SVDFOptions
    | ScatterNdOptions
    | SegmentSumOptions
    | SelectOptions
    | SelectV2Options
    | SequenceRNNOptions
    | ShapeOptions
    | SignOptions
    | SkipGramOptions
    | SliceOptions
    | SoftmaxOptions
    | SpaceToBatchNDOptions
    | SpaceToDepthOptions
    | SparseToDenseOptions
    | SplitOptions
    | SplitVOptions
    | SquareOptions
    | SquaredDifferenceOptions
    | SqueezeOptions
    | StridedSliceOptions
    | SubOptions
    | TileOptions
    | TopKV2Options
    | TransposeConvOptions
    | TransposeOptions
    | UnidirectionalSequenceLSTMOptions
    | UniqueOptions
    | UnpackOptions
    | UnsortedSegmentMaxOptions
    | UnsortedSegmentMinOptions
    | UnsortedSegmentProdOptions
    | UnsortedSegmentSumOptions
    | VarHandleOptions
    | WhereOptions
    | WhileOptions
    | ZerosLikeOptions
    | null,
):
  | ATan2Options
  | AbsOptions
  | AddNOptions
  | AddOptions
  | ArgMaxOptions
  | ArgMinOptions
  | AssignVariableOptions
  | BatchMatMulOptions
  | BatchToSpaceNDOptions
  | BidirectionalSequenceLSTMOptions
  | BidirectionalSequenceRNNOptions
  | BitcastOptions
  | BitwiseXorOptions
  | BroadcastToOptions
  | BucketizeOptions
  | CallOnceOptions
  | CallOptions
  | CastOptions
  | ConcatEmbeddingsOptions
  | ConcatenationOptions
  | Conv2DOptions
  | Conv3DOptions
  | CosOptions
  | CumsumOptions
  | DensifyOptions
  | DepthToSpaceOptions
  | DepthwiseConv2DOptions
  | DequantizeOptions
  | DivOptions
  | DynamicUpdateSliceOptions
  | EmbeddingLookupSparseOptions
  | EqualOptions
  | ExpOptions
  | ExpandDimsOptions
  | FakeQuantOptions
  | FillOptions
  | FloorDivOptions
  | FloorModOptions
  | FullyConnectedOptions
  | GatherNdOptions
  | GatherOptions
  | GeluOptions
  | GreaterEqualOptions
  | GreaterOptions
  | HardSwishOptions
  | HashtableFindOptions
  | HashtableImportOptions
  | HashtableOptions
  | HashtableSizeOptions
  | IfOptions
  | L2NormOptions
  | LSHProjectionOptions
  | LSTMOptions
  | LeakyReluOptions
  | LessEqualOptions
  | LessOptions
  | LocalResponseNormalizationOptions
  | LogSoftmaxOptions
  | LogicalAndOptions
  | LogicalNotOptions
  | LogicalOrOptions
  | MatrixDiagOptions
  | MatrixSetDiagOptions
  | MaximumMinimumOptions
  | MirrorPadOptions
  | MulOptions
  | NegOptions
  | NonMaxSuppressionV4Options
  | NonMaxSuppressionV5Options
  | NotEqualOptions
  | OneHotOptions
  | PackOptions
  | PadOptions
  | PadV2Options
  | Pool2DOptions
  | PowOptions
  | QuantizeOptions
  | RNNOptions
  | RandomOptions
  | RangeOptions
  | RankOptions
  | ReadVariableOptions
  | ReducerOptions
  | ReshapeOptions
  | ResizeBilinearOptions
  | ResizeNearestNeighborOptions
  | ReverseSequenceOptions
  | ReverseV2Options
  | Rfft2dOptions
  | RightShiftOptions
  | SVDFOptions
  | ScatterNdOptions
  | SegmentSumOptions
  | SelectOptions
  | SelectV2Options
  | SequenceRNNOptions
  | ShapeOptions
  | SignOptions
  | SkipGramOptions
  | SliceOptions
  | SoftmaxOptions
  | SpaceToBatchNDOptions
  | SpaceToDepthOptions
  | SparseToDenseOptions
  | SplitOptions
  | SplitVOptions
  | SquareOptions
  | SquaredDifferenceOptions
  | SqueezeOptions
  | StridedSliceOptions
  | SubOptions
  | TileOptions
  | TopKV2Options
  | TransposeConvOptions
  | TransposeOptions
  | UnidirectionalSequenceLSTMOptions
  | UniqueOptions
  | UnpackOptions
  | UnsortedSegmentMaxOptions
  | UnsortedSegmentMinOptions
  | UnsortedSegmentProdOptions
  | UnsortedSegmentSumOptions
  | VarHandleOptions
  | WhereOptions
  | WhileOptions
  | ZerosLikeOptions
  | null {
  switch (BuiltinOptions[type]) {
    case "NONE":
      return null;
    case "Conv2DOptions":
      return accessor(new Conv2DOptions())! as Conv2DOptions;
    case "DepthwiseConv2DOptions":
      return accessor(new DepthwiseConv2DOptions())! as DepthwiseConv2DOptions;
    case "ConcatEmbeddingsOptions":
      return accessor(new ConcatEmbeddingsOptions())! as ConcatEmbeddingsOptions;
    case "LSHProjectionOptions":
      return accessor(new LSHProjectionOptions())! as LSHProjectionOptions;
    case "Pool2DOptions":
      return accessor(new Pool2DOptions())! as Pool2DOptions;
    case "SVDFOptions":
      return accessor(new SVDFOptions())! as SVDFOptions;
    case "RNNOptions":
      return accessor(new RNNOptions())! as RNNOptions;
    case "FullyConnectedOptions":
      return accessor(new FullyConnectedOptions())! as FullyConnectedOptions;
    case "SoftmaxOptions":
      return accessor(new SoftmaxOptions())! as SoftmaxOptions;
    case "ConcatenationOptions":
      return accessor(new ConcatenationOptions())! as ConcatenationOptions;
    case "AddOptions":
      return accessor(new AddOptions())! as AddOptions;
    case "L2NormOptions":
      return accessor(new L2NormOptions())! as L2NormOptions;
    case "LocalResponseNormalizationOptions":
      return accessor(
        new LocalResponseNormalizationOptions(),
      )! as LocalResponseNormalizationOptions;
    case "LSTMOptions":
      return accessor(new LSTMOptions())! as LSTMOptions;
    case "ResizeBilinearOptions":
      return accessor(new ResizeBilinearOptions())! as ResizeBilinearOptions;
    case "CallOptions":
      return accessor(new CallOptions())! as CallOptions;
    case "ReshapeOptions":
      return accessor(new ReshapeOptions())! as ReshapeOptions;
    case "SkipGramOptions":
      return accessor(new SkipGramOptions())! as SkipGramOptions;
    case "SpaceToDepthOptions":
      return accessor(new SpaceToDepthOptions())! as SpaceToDepthOptions;
    case "EmbeddingLookupSparseOptions":
      return accessor(new EmbeddingLookupSparseOptions())! as EmbeddingLookupSparseOptions;
    case "MulOptions":
      return accessor(new MulOptions())! as MulOptions;
    case "PadOptions":
      return accessor(new PadOptions())! as PadOptions;
    case "GatherOptions":
      return accessor(new GatherOptions())! as GatherOptions;
    case "BatchToSpaceNDOptions":
      return accessor(new BatchToSpaceNDOptions())! as BatchToSpaceNDOptions;
    case "SpaceToBatchNDOptions":
      return accessor(new SpaceToBatchNDOptions())! as SpaceToBatchNDOptions;
    case "TransposeOptions":
      return accessor(new TransposeOptions())! as TransposeOptions;
    case "ReducerOptions":
      return accessor(new ReducerOptions())! as ReducerOptions;
    case "SubOptions":
      return accessor(new SubOptions())! as SubOptions;
    case "DivOptions":
      return accessor(new DivOptions())! as DivOptions;
    case "SqueezeOptions":
      return accessor(new SqueezeOptions())! as SqueezeOptions;
    case "SequenceRNNOptions":
      return accessor(new SequenceRNNOptions())! as SequenceRNNOptions;
    case "StridedSliceOptions":
      return accessor(new StridedSliceOptions())! as StridedSliceOptions;
    case "ExpOptions":
      return accessor(new ExpOptions())! as ExpOptions;
    case "TopKV2Options":
      return accessor(new TopKV2Options())! as TopKV2Options;
    case "SplitOptions":
      return accessor(new SplitOptions())! as SplitOptions;
    case "LogSoftmaxOptions":
      return accessor(new LogSoftmaxOptions())! as LogSoftmaxOptions;
    case "CastOptions":
      return accessor(new CastOptions())! as CastOptions;
    case "DequantizeOptions":
      return accessor(new DequantizeOptions())! as DequantizeOptions;
    case "MaximumMinimumOptions":
      return accessor(new MaximumMinimumOptions())! as MaximumMinimumOptions;
    case "ArgMaxOptions":
      return accessor(new ArgMaxOptions())! as ArgMaxOptions;
    case "LessOptions":
      return accessor(new LessOptions())! as LessOptions;
    case "NegOptions":
      return accessor(new NegOptions())! as NegOptions;
    case "PadV2Options":
      return accessor(new PadV2Options())! as PadV2Options;
    case "GreaterOptions":
      return accessor(new GreaterOptions())! as GreaterOptions;
    case "GreaterEqualOptions":
      return accessor(new GreaterEqualOptions())! as GreaterEqualOptions;
    case "LessEqualOptions":
      return accessor(new LessEqualOptions())! as LessEqualOptions;
    case "SelectOptions":
      return accessor(new SelectOptions())! as SelectOptions;
    case "SliceOptions":
      return accessor(new SliceOptions())! as SliceOptions;
    case "TransposeConvOptions":
      return accessor(new TransposeConvOptions())! as TransposeConvOptions;
    case "SparseToDenseOptions":
      return accessor(new SparseToDenseOptions())! as SparseToDenseOptions;
    case "TileOptions":
      return accessor(new TileOptions())! as TileOptions;
    case "ExpandDimsOptions":
      return accessor(new ExpandDimsOptions())! as ExpandDimsOptions;
    case "EqualOptions":
      return accessor(new EqualOptions())! as EqualOptions;
    case "NotEqualOptions":
      return accessor(new NotEqualOptions())! as NotEqualOptions;
    case "ShapeOptions":
      return accessor(new ShapeOptions())! as ShapeOptions;
    case "PowOptions":
      return accessor(new PowOptions())! as PowOptions;
    case "ArgMinOptions":
      return accessor(new ArgMinOptions())! as ArgMinOptions;
    case "FakeQuantOptions":
      return accessor(new FakeQuantOptions())! as FakeQuantOptions;
    case "PackOptions":
      return accessor(new PackOptions())! as PackOptions;
    case "LogicalOrOptions":
      return accessor(new LogicalOrOptions())! as LogicalOrOptions;
    case "OneHotOptions":
      return accessor(new OneHotOptions())! as OneHotOptions;
    case "LogicalAndOptions":
      return accessor(new LogicalAndOptions())! as LogicalAndOptions;
    case "LogicalNotOptions":
      return accessor(new LogicalNotOptions())! as LogicalNotOptions;
    case "UnpackOptions":
      return accessor(new UnpackOptions())! as UnpackOptions;
    case "FloorDivOptions":
      return accessor(new FloorDivOptions())! as FloorDivOptions;
    case "SquareOptions":
      return accessor(new SquareOptions())! as SquareOptions;
    case "ZerosLikeOptions":
      return accessor(new ZerosLikeOptions())! as ZerosLikeOptions;
    case "FillOptions":
      return accessor(new FillOptions())! as FillOptions;
    case "BidirectionalSequenceLSTMOptions":
      return accessor(new BidirectionalSequenceLSTMOptions())! as BidirectionalSequenceLSTMOptions;
    case "BidirectionalSequenceRNNOptions":
      return accessor(new BidirectionalSequenceRNNOptions())! as BidirectionalSequenceRNNOptions;
    case "UnidirectionalSequenceLSTMOptions":
      return accessor(
        new UnidirectionalSequenceLSTMOptions(),
      )! as UnidirectionalSequenceLSTMOptions;
    case "FloorModOptions":
      return accessor(new FloorModOptions())! as FloorModOptions;
    case "RangeOptions":
      return accessor(new RangeOptions())! as RangeOptions;
    case "ResizeNearestNeighborOptions":
      return accessor(new ResizeNearestNeighborOptions())! as ResizeNearestNeighborOptions;
    case "LeakyReluOptions":
      return accessor(new LeakyReluOptions())! as LeakyReluOptions;
    case "SquaredDifferenceOptions":
      return accessor(new SquaredDifferenceOptions())! as SquaredDifferenceOptions;
    case "MirrorPadOptions":
      return accessor(new MirrorPadOptions())! as MirrorPadOptions;
    case "AbsOptions":
      return accessor(new AbsOptions())! as AbsOptions;
    case "SplitVOptions":
      return accessor(new SplitVOptions())! as SplitVOptions;
    case "UniqueOptions":
      return accessor(new UniqueOptions())! as UniqueOptions;
    case "ReverseV2Options":
      return accessor(new ReverseV2Options())! as ReverseV2Options;
    case "AddNOptions":
      return accessor(new AddNOptions())! as AddNOptions;
    case "GatherNdOptions":
      return accessor(new GatherNdOptions())! as GatherNdOptions;
    case "CosOptions":
      return accessor(new CosOptions())! as CosOptions;
    case "WhereOptions":
      return accessor(new WhereOptions())! as WhereOptions;
    case "RankOptions":
      return accessor(new RankOptions())! as RankOptions;
    case "ReverseSequenceOptions":
      return accessor(new ReverseSequenceOptions())! as ReverseSequenceOptions;
    case "MatrixDiagOptions":
      return accessor(new MatrixDiagOptions())! as MatrixDiagOptions;
    case "QuantizeOptions":
      return accessor(new QuantizeOptions())! as QuantizeOptions;
    case "MatrixSetDiagOptions":
      return accessor(new MatrixSetDiagOptions())! as MatrixSetDiagOptions;
    case "HardSwishOptions":
      return accessor(new HardSwishOptions())! as HardSwishOptions;
    case "IfOptions":
      return accessor(new IfOptions())! as IfOptions;
    case "WhileOptions":
      return accessor(new WhileOptions())! as WhileOptions;
    case "DepthToSpaceOptions":
      return accessor(new DepthToSpaceOptions())! as DepthToSpaceOptions;
    case "NonMaxSuppressionV4Options":
      return accessor(new NonMaxSuppressionV4Options())! as NonMaxSuppressionV4Options;
    case "NonMaxSuppressionV5Options":
      return accessor(new NonMaxSuppressionV5Options())! as NonMaxSuppressionV5Options;
    case "ScatterNdOptions":
      return accessor(new ScatterNdOptions())! as ScatterNdOptions;
    case "SelectV2Options":
      return accessor(new SelectV2Options())! as SelectV2Options;
    case "DensifyOptions":
      return accessor(new DensifyOptions())! as DensifyOptions;
    case "SegmentSumOptions":
      return accessor(new SegmentSumOptions())! as SegmentSumOptions;
    case "BatchMatMulOptions":
      return accessor(new BatchMatMulOptions())! as BatchMatMulOptions;
    case "CumsumOptions":
      return accessor(new CumsumOptions())! as CumsumOptions;
    case "CallOnceOptions":
      return accessor(new CallOnceOptions())! as CallOnceOptions;
    case "BroadcastToOptions":
      return accessor(new BroadcastToOptions())! as BroadcastToOptions;
    case "Rfft2dOptions":
      return accessor(new Rfft2dOptions())! as Rfft2dOptions;
    case "Conv3DOptions":
      return accessor(new Conv3DOptions())! as Conv3DOptions;
    case "HashtableOptions":
      return accessor(new HashtableOptions())! as HashtableOptions;
    case "HashtableFindOptions":
      return accessor(new HashtableFindOptions())! as HashtableFindOptions;
    case "HashtableImportOptions":
      return accessor(new HashtableImportOptions())! as HashtableImportOptions;
    case "HashtableSizeOptions":
      return accessor(new HashtableSizeOptions())! as HashtableSizeOptions;
    case "VarHandleOptions":
      return accessor(new VarHandleOptions())! as VarHandleOptions;
    case "ReadVariableOptions":
      return accessor(new ReadVariableOptions())! as ReadVariableOptions;
    case "AssignVariableOptions":
      return accessor(new AssignVariableOptions())! as AssignVariableOptions;
    case "RandomOptions":
      return accessor(new RandomOptions())! as RandomOptions;
    case "BucketizeOptions":
      return accessor(new BucketizeOptions())! as BucketizeOptions;
    case "GeluOptions":
      return accessor(new GeluOptions())! as GeluOptions;
    case "DynamicUpdateSliceOptions":
      return accessor(new DynamicUpdateSliceOptions())! as DynamicUpdateSliceOptions;
    case "UnsortedSegmentProdOptions":
      return accessor(new UnsortedSegmentProdOptions())! as UnsortedSegmentProdOptions;
    case "UnsortedSegmentMaxOptions":
      return accessor(new UnsortedSegmentMaxOptions())! as UnsortedSegmentMaxOptions;
    case "UnsortedSegmentMinOptions":
      return accessor(new UnsortedSegmentMinOptions())! as UnsortedSegmentMinOptions;
    case "UnsortedSegmentSumOptions":
      return accessor(new UnsortedSegmentSumOptions())! as UnsortedSegmentSumOptions;
    case "ATan2Options":
      return accessor(new ATan2Options())! as ATan2Options;
    case "SignOptions":
      return accessor(new SignOptions())! as SignOptions;
    case "BitcastOptions":
      return accessor(new BitcastOptions())! as BitcastOptions;
    case "BitwiseXorOptions":
      return accessor(new BitwiseXorOptions())! as BitwiseXorOptions;
    case "RightShiftOptions":
      return accessor(new RightShiftOptions())! as RightShiftOptions;
    default:
      return null;
  }
}

export function unionListToBuiltinOptions(
  type: BuiltinOptions,
  accessor: (
    index: number,
    obj:
      | ATan2Options
      | AbsOptions
      | AddNOptions
      | AddOptions
      | ArgMaxOptions
      | ArgMinOptions
      | AssignVariableOptions
      | BatchMatMulOptions
      | BatchToSpaceNDOptions
      | BidirectionalSequenceLSTMOptions
      | BidirectionalSequenceRNNOptions
      | BitcastOptions
      | BitwiseXorOptions
      | BroadcastToOptions
      | BucketizeOptions
      | CallOnceOptions
      | CallOptions
      | CastOptions
      | ConcatEmbeddingsOptions
      | ConcatenationOptions
      | Conv2DOptions
      | Conv3DOptions
      | CosOptions
      | CumsumOptions
      | DensifyOptions
      | DepthToSpaceOptions
      | DepthwiseConv2DOptions
      | DequantizeOptions
      | DivOptions
      | DynamicUpdateSliceOptions
      | EmbeddingLookupSparseOptions
      | EqualOptions
      | ExpOptions
      | ExpandDimsOptions
      | FakeQuantOptions
      | FillOptions
      | FloorDivOptions
      | FloorModOptions
      | FullyConnectedOptions
      | GatherNdOptions
      | GatherOptions
      | GeluOptions
      | GreaterEqualOptions
      | GreaterOptions
      | HardSwishOptions
      | HashtableFindOptions
      | HashtableImportOptions
      | HashtableOptions
      | HashtableSizeOptions
      | IfOptions
      | L2NormOptions
      | LSHProjectionOptions
      | LSTMOptions
      | LeakyReluOptions
      | LessEqualOptions
      | LessOptions
      | LocalResponseNormalizationOptions
      | LogSoftmaxOptions
      | LogicalAndOptions
      | LogicalNotOptions
      | LogicalOrOptions
      | MatrixDiagOptions
      | MatrixSetDiagOptions
      | MaximumMinimumOptions
      | MirrorPadOptions
      | MulOptions
      | NegOptions
      | NonMaxSuppressionV4Options
      | NonMaxSuppressionV5Options
      | NotEqualOptions
      | OneHotOptions
      | PackOptions
      | PadOptions
      | PadV2Options
      | Pool2DOptions
      | PowOptions
      | QuantizeOptions
      | RNNOptions
      | RandomOptions
      | RangeOptions
      | RankOptions
      | ReadVariableOptions
      | ReducerOptions
      | ReshapeOptions
      | ResizeBilinearOptions
      | ResizeNearestNeighborOptions
      | ReverseSequenceOptions
      | ReverseV2Options
      | Rfft2dOptions
      | RightShiftOptions
      | SVDFOptions
      | ScatterNdOptions
      | SegmentSumOptions
      | SelectOptions
      | SelectV2Options
      | SequenceRNNOptions
      | ShapeOptions
      | SignOptions
      | SkipGramOptions
      | SliceOptions
      | SoftmaxOptions
      | SpaceToBatchNDOptions
      | SpaceToDepthOptions
      | SparseToDenseOptions
      | SplitOptions
      | SplitVOptions
      | SquareOptions
      | SquaredDifferenceOptions
      | SqueezeOptions
      | StridedSliceOptions
      | SubOptions
      | TileOptions
      | TopKV2Options
      | TransposeConvOptions
      | TransposeOptions
      | UnidirectionalSequenceLSTMOptions
      | UniqueOptions
      | UnpackOptions
      | UnsortedSegmentMaxOptions
      | UnsortedSegmentMinOptions
      | UnsortedSegmentProdOptions
      | UnsortedSegmentSumOptions
      | VarHandleOptions
      | WhereOptions
      | WhileOptions
      | ZerosLikeOptions,
  ) =>
    | ATan2Options
    | AbsOptions
    | AddNOptions
    | AddOptions
    | ArgMaxOptions
    | ArgMinOptions
    | AssignVariableOptions
    | BatchMatMulOptions
    | BatchToSpaceNDOptions
    | BidirectionalSequenceLSTMOptions
    | BidirectionalSequenceRNNOptions
    | BitcastOptions
    | BitwiseXorOptions
    | BroadcastToOptions
    | BucketizeOptions
    | CallOnceOptions
    | CallOptions
    | CastOptions
    | ConcatEmbeddingsOptions
    | ConcatenationOptions
    | Conv2DOptions
    | Conv3DOptions
    | CosOptions
    | CumsumOptions
    | DensifyOptions
    | DepthToSpaceOptions
    | DepthwiseConv2DOptions
    | DequantizeOptions
    | DivOptions
    | DynamicUpdateSliceOptions
    | EmbeddingLookupSparseOptions
    | EqualOptions
    | ExpOptions
    | ExpandDimsOptions
    | FakeQuantOptions
    | FillOptions
    | FloorDivOptions
    | FloorModOptions
    | FullyConnectedOptions
    | GatherNdOptions
    | GatherOptions
    | GeluOptions
    | GreaterEqualOptions
    | GreaterOptions
    | HardSwishOptions
    | HashtableFindOptions
    | HashtableImportOptions
    | HashtableOptions
    | HashtableSizeOptions
    | IfOptions
    | L2NormOptions
    | LSHProjectionOptions
    | LSTMOptions
    | LeakyReluOptions
    | LessEqualOptions
    | LessOptions
    | LocalResponseNormalizationOptions
    | LogSoftmaxOptions
    | LogicalAndOptions
    | LogicalNotOptions
    | LogicalOrOptions
    | MatrixDiagOptions
    | MatrixSetDiagOptions
    | MaximumMinimumOptions
    | MirrorPadOptions
    | MulOptions
    | NegOptions
    | NonMaxSuppressionV4Options
    | NonMaxSuppressionV5Options
    | NotEqualOptions
    | OneHotOptions
    | PackOptions
    | PadOptions
    | PadV2Options
    | Pool2DOptions
    | PowOptions
    | QuantizeOptions
    | RNNOptions
    | RandomOptions
    | RangeOptions
    | RankOptions
    | ReadVariableOptions
    | ReducerOptions
    | ReshapeOptions
    | ResizeBilinearOptions
    | ResizeNearestNeighborOptions
    | ReverseSequenceOptions
    | ReverseV2Options
    | Rfft2dOptions
    | RightShiftOptions
    | SVDFOptions
    | ScatterNdOptions
    | SegmentSumOptions
    | SelectOptions
    | SelectV2Options
    | SequenceRNNOptions
    | ShapeOptions
    | SignOptions
    | SkipGramOptions
    | SliceOptions
    | SoftmaxOptions
    | SpaceToBatchNDOptions
    | SpaceToDepthOptions
    | SparseToDenseOptions
    | SplitOptions
    | SplitVOptions
    | SquareOptions
    | SquaredDifferenceOptions
    | SqueezeOptions
    | StridedSliceOptions
    | SubOptions
    | TileOptions
    | TopKV2Options
    | TransposeConvOptions
    | TransposeOptions
    | UnidirectionalSequenceLSTMOptions
    | UniqueOptions
    | UnpackOptions
    | UnsortedSegmentMaxOptions
    | UnsortedSegmentMinOptions
    | UnsortedSegmentProdOptions
    | UnsortedSegmentSumOptions
    | VarHandleOptions
    | WhereOptions
    | WhileOptions
    | ZerosLikeOptions
    | null,
  index: number,
):
  | ATan2Options
  | AbsOptions
  | AddNOptions
  | AddOptions
  | ArgMaxOptions
  | ArgMinOptions
  | AssignVariableOptions
  | BatchMatMulOptions
  | BatchToSpaceNDOptions
  | BidirectionalSequenceLSTMOptions
  | BidirectionalSequenceRNNOptions
  | BitcastOptions
  | BitwiseXorOptions
  | BroadcastToOptions
  | BucketizeOptions
  | CallOnceOptions
  | CallOptions
  | CastOptions
  | ConcatEmbeddingsOptions
  | ConcatenationOptions
  | Conv2DOptions
  | Conv3DOptions
  | CosOptions
  | CumsumOptions
  | DensifyOptions
  | DepthToSpaceOptions
  | DepthwiseConv2DOptions
  | DequantizeOptions
  | DivOptions
  | DynamicUpdateSliceOptions
  | EmbeddingLookupSparseOptions
  | EqualOptions
  | ExpOptions
  | ExpandDimsOptions
  | FakeQuantOptions
  | FillOptions
  | FloorDivOptions
  | FloorModOptions
  | FullyConnectedOptions
  | GatherNdOptions
  | GatherOptions
  | GeluOptions
  | GreaterEqualOptions
  | GreaterOptions
  | HardSwishOptions
  | HashtableFindOptions
  | HashtableImportOptions
  | HashtableOptions
  | HashtableSizeOptions
  | IfOptions
  | L2NormOptions
  | LSHProjectionOptions
  | LSTMOptions
  | LeakyReluOptions
  | LessEqualOptions
  | LessOptions
  | LocalResponseNormalizationOptions
  | LogSoftmaxOptions
  | LogicalAndOptions
  | LogicalNotOptions
  | LogicalOrOptions
  | MatrixDiagOptions
  | MatrixSetDiagOptions
  | MaximumMinimumOptions
  | MirrorPadOptions
  | MulOptions
  | NegOptions
  | NonMaxSuppressionV4Options
  | NonMaxSuppressionV5Options
  | NotEqualOptions
  | OneHotOptions
  | PackOptions
  | PadOptions
  | PadV2Options
  | Pool2DOptions
  | PowOptions
  | QuantizeOptions
  | RNNOptions
  | RandomOptions
  | RangeOptions
  | RankOptions
  | ReadVariableOptions
  | ReducerOptions
  | ReshapeOptions
  | ResizeBilinearOptions
  | ResizeNearestNeighborOptions
  | ReverseSequenceOptions
  | ReverseV2Options
  | Rfft2dOptions
  | RightShiftOptions
  | SVDFOptions
  | ScatterNdOptions
  | SegmentSumOptions
  | SelectOptions
  | SelectV2Options
  | SequenceRNNOptions
  | ShapeOptions
  | SignOptions
  | SkipGramOptions
  | SliceOptions
  | SoftmaxOptions
  | SpaceToBatchNDOptions
  | SpaceToDepthOptions
  | SparseToDenseOptions
  | SplitOptions
  | SplitVOptions
  | SquareOptions
  | SquaredDifferenceOptions
  | SqueezeOptions
  | StridedSliceOptions
  | SubOptions
  | TileOptions
  | TopKV2Options
  | TransposeConvOptions
  | TransposeOptions
  | UnidirectionalSequenceLSTMOptions
  | UniqueOptions
  | UnpackOptions
  | UnsortedSegmentMaxOptions
  | UnsortedSegmentMinOptions
  | UnsortedSegmentProdOptions
  | UnsortedSegmentSumOptions
  | VarHandleOptions
  | WhereOptions
  | WhileOptions
  | ZerosLikeOptions
  | null {
  switch (BuiltinOptions[type]) {
    case "NONE":
      return null;
    case "Conv2DOptions":
      return accessor(index, new Conv2DOptions())! as Conv2DOptions;
    case "DepthwiseConv2DOptions":
      return accessor(index, new DepthwiseConv2DOptions())! as DepthwiseConv2DOptions;
    case "ConcatEmbeddingsOptions":
      return accessor(index, new ConcatEmbeddingsOptions())! as ConcatEmbeddingsOptions;
    case "LSHProjectionOptions":
      return accessor(index, new LSHProjectionOptions())! as LSHProjectionOptions;
    case "Pool2DOptions":
      return accessor(index, new Pool2DOptions())! as Pool2DOptions;
    case "SVDFOptions":
      return accessor(index, new SVDFOptions())! as SVDFOptions;
    case "RNNOptions":
      return accessor(index, new RNNOptions())! as RNNOptions;
    case "FullyConnectedOptions":
      return accessor(index, new FullyConnectedOptions())! as FullyConnectedOptions;
    case "SoftmaxOptions":
      return accessor(index, new SoftmaxOptions())! as SoftmaxOptions;
    case "ConcatenationOptions":
      return accessor(index, new ConcatenationOptions())! as ConcatenationOptions;
    case "AddOptions":
      return accessor(index, new AddOptions())! as AddOptions;
    case "L2NormOptions":
      return accessor(index, new L2NormOptions())! as L2NormOptions;
    case "LocalResponseNormalizationOptions":
      return accessor(
        index,
        new LocalResponseNormalizationOptions(),
      )! as LocalResponseNormalizationOptions;
    case "LSTMOptions":
      return accessor(index, new LSTMOptions())! as LSTMOptions;
    case "ResizeBilinearOptions":
      return accessor(index, new ResizeBilinearOptions())! as ResizeBilinearOptions;
    case "CallOptions":
      return accessor(index, new CallOptions())! as CallOptions;
    case "ReshapeOptions":
      return accessor(index, new ReshapeOptions())! as ReshapeOptions;
    case "SkipGramOptions":
      return accessor(index, new SkipGramOptions())! as SkipGramOptions;
    case "SpaceToDepthOptions":
      return accessor(index, new SpaceToDepthOptions())! as SpaceToDepthOptions;
    case "EmbeddingLookupSparseOptions":
      return accessor(index, new EmbeddingLookupSparseOptions())! as EmbeddingLookupSparseOptions;
    case "MulOptions":
      return accessor(index, new MulOptions())! as MulOptions;
    case "PadOptions":
      return accessor(index, new PadOptions())! as PadOptions;
    case "GatherOptions":
      return accessor(index, new GatherOptions())! as GatherOptions;
    case "BatchToSpaceNDOptions":
      return accessor(index, new BatchToSpaceNDOptions())! as BatchToSpaceNDOptions;
    case "SpaceToBatchNDOptions":
      return accessor(index, new SpaceToBatchNDOptions())! as SpaceToBatchNDOptions;
    case "TransposeOptions":
      return accessor(index, new TransposeOptions())! as TransposeOptions;
    case "ReducerOptions":
      return accessor(index, new ReducerOptions())! as ReducerOptions;
    case "SubOptions":
      return accessor(index, new SubOptions())! as SubOptions;
    case "DivOptions":
      return accessor(index, new DivOptions())! as DivOptions;
    case "SqueezeOptions":
      return accessor(index, new SqueezeOptions())! as SqueezeOptions;
    case "SequenceRNNOptions":
      return accessor(index, new SequenceRNNOptions())! as SequenceRNNOptions;
    case "StridedSliceOptions":
      return accessor(index, new StridedSliceOptions())! as StridedSliceOptions;
    case "ExpOptions":
      return accessor(index, new ExpOptions())! as ExpOptions;
    case "TopKV2Options":
      return accessor(index, new TopKV2Options())! as TopKV2Options;
    case "SplitOptions":
      return accessor(index, new SplitOptions())! as SplitOptions;
    case "LogSoftmaxOptions":
      return accessor(index, new LogSoftmaxOptions())! as LogSoftmaxOptions;
    case "CastOptions":
      return accessor(index, new CastOptions())! as CastOptions;
    case "DequantizeOptions":
      return accessor(index, new DequantizeOptions())! as DequantizeOptions;
    case "MaximumMinimumOptions":
      return accessor(index, new MaximumMinimumOptions())! as MaximumMinimumOptions;
    case "ArgMaxOptions":
      return accessor(index, new ArgMaxOptions())! as ArgMaxOptions;
    case "LessOptions":
      return accessor(index, new LessOptions())! as LessOptions;
    case "NegOptions":
      return accessor(index, new NegOptions())! as NegOptions;
    case "PadV2Options":
      return accessor(index, new PadV2Options())! as PadV2Options;
    case "GreaterOptions":
      return accessor(index, new GreaterOptions())! as GreaterOptions;
    case "GreaterEqualOptions":
      return accessor(index, new GreaterEqualOptions())! as GreaterEqualOptions;
    case "LessEqualOptions":
      return accessor(index, new LessEqualOptions())! as LessEqualOptions;
    case "SelectOptions":
      return accessor(index, new SelectOptions())! as SelectOptions;
    case "SliceOptions":
      return accessor(index, new SliceOptions())! as SliceOptions;
    case "TransposeConvOptions":
      return accessor(index, new TransposeConvOptions())! as TransposeConvOptions;
    case "SparseToDenseOptions":
      return accessor(index, new SparseToDenseOptions())! as SparseToDenseOptions;
    case "TileOptions":
      return accessor(index, new TileOptions())! as TileOptions;
    case "ExpandDimsOptions":
      return accessor(index, new ExpandDimsOptions())! as ExpandDimsOptions;
    case "EqualOptions":
      return accessor(index, new EqualOptions())! as EqualOptions;
    case "NotEqualOptions":
      return accessor(index, new NotEqualOptions())! as NotEqualOptions;
    case "ShapeOptions":
      return accessor(index, new ShapeOptions())! as ShapeOptions;
    case "PowOptions":
      return accessor(index, new PowOptions())! as PowOptions;
    case "ArgMinOptions":
      return accessor(index, new ArgMinOptions())! as ArgMinOptions;
    case "FakeQuantOptions":
      return accessor(index, new FakeQuantOptions())! as FakeQuantOptions;
    case "PackOptions":
      return accessor(index, new PackOptions())! as PackOptions;
    case "LogicalOrOptions":
      return accessor(index, new LogicalOrOptions())! as LogicalOrOptions;
    case "OneHotOptions":
      return accessor(index, new OneHotOptions())! as OneHotOptions;
    case "LogicalAndOptions":
      return accessor(index, new LogicalAndOptions())! as LogicalAndOptions;
    case "LogicalNotOptions":
      return accessor(index, new LogicalNotOptions())! as LogicalNotOptions;
    case "UnpackOptions":
      return accessor(index, new UnpackOptions())! as UnpackOptions;
    case "FloorDivOptions":
      return accessor(index, new FloorDivOptions())! as FloorDivOptions;
    case "SquareOptions":
      return accessor(index, new SquareOptions())! as SquareOptions;
    case "ZerosLikeOptions":
      return accessor(index, new ZerosLikeOptions())! as ZerosLikeOptions;
    case "FillOptions":
      return accessor(index, new FillOptions())! as FillOptions;
    case "BidirectionalSequenceLSTMOptions":
      return accessor(
        index,
        new BidirectionalSequenceLSTMOptions(),
      )! as BidirectionalSequenceLSTMOptions;
    case "BidirectionalSequenceRNNOptions":
      return accessor(
        index,
        new BidirectionalSequenceRNNOptions(),
      )! as BidirectionalSequenceRNNOptions;
    case "UnidirectionalSequenceLSTMOptions":
      return accessor(
        index,
        new UnidirectionalSequenceLSTMOptions(),
      )! as UnidirectionalSequenceLSTMOptions;
    case "FloorModOptions":
      return accessor(index, new FloorModOptions())! as FloorModOptions;
    case "RangeOptions":
      return accessor(index, new RangeOptions())! as RangeOptions;
    case "ResizeNearestNeighborOptions":
      return accessor(index, new ResizeNearestNeighborOptions())! as ResizeNearestNeighborOptions;
    case "LeakyReluOptions":
      return accessor(index, new LeakyReluOptions())! as LeakyReluOptions;
    case "SquaredDifferenceOptions":
      return accessor(index, new SquaredDifferenceOptions())! as SquaredDifferenceOptions;
    case "MirrorPadOptions":
      return accessor(index, new MirrorPadOptions())! as MirrorPadOptions;
    case "AbsOptions":
      return accessor(index, new AbsOptions())! as AbsOptions;
    case "SplitVOptions":
      return accessor(index, new SplitVOptions())! as SplitVOptions;
    case "UniqueOptions":
      return accessor(index, new UniqueOptions())! as UniqueOptions;
    case "ReverseV2Options":
      return accessor(index, new ReverseV2Options())! as ReverseV2Options;
    case "AddNOptions":
      return accessor(index, new AddNOptions())! as AddNOptions;
    case "GatherNdOptions":
      return accessor(index, new GatherNdOptions())! as GatherNdOptions;
    case "CosOptions":
      return accessor(index, new CosOptions())! as CosOptions;
    case "WhereOptions":
      return accessor(index, new WhereOptions())! as WhereOptions;
    case "RankOptions":
      return accessor(index, new RankOptions())! as RankOptions;
    case "ReverseSequenceOptions":
      return accessor(index, new ReverseSequenceOptions())! as ReverseSequenceOptions;
    case "MatrixDiagOptions":
      return accessor(index, new MatrixDiagOptions())! as MatrixDiagOptions;
    case "QuantizeOptions":
      return accessor(index, new QuantizeOptions())! as QuantizeOptions;
    case "MatrixSetDiagOptions":
      return accessor(index, new MatrixSetDiagOptions())! as MatrixSetDiagOptions;
    case "HardSwishOptions":
      return accessor(index, new HardSwishOptions())! as HardSwishOptions;
    case "IfOptions":
      return accessor(index, new IfOptions())! as IfOptions;
    case "WhileOptions":
      return accessor(index, new WhileOptions())! as WhileOptions;
    case "DepthToSpaceOptions":
      return accessor(index, new DepthToSpaceOptions())! as DepthToSpaceOptions;
    case "NonMaxSuppressionV4Options":
      return accessor(index, new NonMaxSuppressionV4Options())! as NonMaxSuppressionV4Options;
    case "NonMaxSuppressionV5Options":
      return accessor(index, new NonMaxSuppressionV5Options())! as NonMaxSuppressionV5Options;
    case "ScatterNdOptions":
      return accessor(index, new ScatterNdOptions())! as ScatterNdOptions;
    case "SelectV2Options":
      return accessor(index, new SelectV2Options())! as SelectV2Options;
    case "DensifyOptions":
      return accessor(index, new DensifyOptions())! as DensifyOptions;
    case "SegmentSumOptions":
      return accessor(index, new SegmentSumOptions())! as SegmentSumOptions;
    case "BatchMatMulOptions":
      return accessor(index, new BatchMatMulOptions())! as BatchMatMulOptions;
    case "CumsumOptions":
      return accessor(index, new CumsumOptions())! as CumsumOptions;
    case "CallOnceOptions":
      return accessor(index, new CallOnceOptions())! as CallOnceOptions;
    case "BroadcastToOptions":
      return accessor(index, new BroadcastToOptions())! as BroadcastToOptions;
    case "Rfft2dOptions":
      return accessor(index, new Rfft2dOptions())! as Rfft2dOptions;
    case "Conv3DOptions":
      return accessor(index, new Conv3DOptions())! as Conv3DOptions;
    case "HashtableOptions":
      return accessor(index, new HashtableOptions())! as HashtableOptions;
    case "HashtableFindOptions":
      return accessor(index, new HashtableFindOptions())! as HashtableFindOptions;
    case "HashtableImportOptions":
      return accessor(index, new HashtableImportOptions())! as HashtableImportOptions;
    case "HashtableSizeOptions":
      return accessor(index, new HashtableSizeOptions())! as HashtableSizeOptions;
    case "VarHandleOptions":
      return accessor(index, new VarHandleOptions())! as VarHandleOptions;
    case "ReadVariableOptions":
      return accessor(index, new ReadVariableOptions())! as ReadVariableOptions;
    case "AssignVariableOptions":
      return accessor(index, new AssignVariableOptions())! as AssignVariableOptions;
    case "RandomOptions":
      return accessor(index, new RandomOptions())! as RandomOptions;
    case "BucketizeOptions":
      return accessor(index, new BucketizeOptions())! as BucketizeOptions;
    case "GeluOptions":
      return accessor(index, new GeluOptions())! as GeluOptions;
    case "DynamicUpdateSliceOptions":
      return accessor(index, new DynamicUpdateSliceOptions())! as DynamicUpdateSliceOptions;
    case "UnsortedSegmentProdOptions":
      return accessor(index, new UnsortedSegmentProdOptions())! as UnsortedSegmentProdOptions;
    case "UnsortedSegmentMaxOptions":
      return accessor(index, new UnsortedSegmentMaxOptions())! as UnsortedSegmentMaxOptions;
    case "UnsortedSegmentMinOptions":
      return accessor(index, new UnsortedSegmentMinOptions())! as UnsortedSegmentMinOptions;
    case "UnsortedSegmentSumOptions":
      return accessor(index, new UnsortedSegmentSumOptions())! as UnsortedSegmentSumOptions;
    case "ATan2Options":
      return accessor(index, new ATan2Options())! as ATan2Options;
    case "SignOptions":
      return accessor(index, new SignOptions())! as SignOptions;
    case "BitcastOptions":
      return accessor(index, new BitcastOptions())! as BitcastOptions;
    case "BitwiseXorOptions":
      return accessor(index, new BitwiseXorOptions())! as BitwiseXorOptions;
    case "RightShiftOptions":
      return accessor(index, new RightShiftOptions())! as RightShiftOptions;
    default:
      return null;
  }
}
